from __future__ import annotations

from typing import Any

from kdenlive_mcp.services.timeline_service import (
    add_timeline_clip,
    apply_timeline_edits,
    create_timeline_from_rough_cut_plan,
    create_timeline_track,
    duplicate_timeline_clip,
    export_timeline_to_mlt_xml,
    export_timeline_to_kdenlive_template,
    inspect_timeline,
    insert_timeline_gap,
    move_timeline_clip,
    remove_timeline_gap,
    remove_timeline_clip,
    remove_timeline_track,
    save_timeline,
    split_timeline_clip,
    trim_timeline_clip,
    update_timeline_track,
    validate_timeline,
)


TOOLS: dict[str, dict[str, Any]] = {
    "create_timeline_from_rough_cut_plan": {
        "description": "Convert a persisted rough-cut plan into an MCP timeline document without writing Kdenlive XML.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "plan_file": {"type": "string"},
                "fps": {"type": "number", "default": 30.0},
                "width": {"type": "integer", "default": 1080},
                "height": {"type": "integer", "default": 1920},
            },
            "required": ["plan_file"],
            "additionalProperties": False,
        },
        "handler": create_timeline_from_rough_cut_plan,
    },
    "save_timeline": {
        "description": "Persist an MCP timeline document into an allowed output directory.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline": {"type": "object"},
                "output_directory": {"type": "string"},
                "name": {"type": "string", "default": "timeline"},
                "overwrite": {"type": "boolean", "default": False},
            },
            "required": ["timeline", "output_directory"],
            "additionalProperties": False,
        },
        "handler": save_timeline,
    },
    "inspect_timeline": {
        "description": "Load and validate an MCP timeline document from an allowed output directory.",
        "inputSchema": {
            "type": "object",
            "properties": {"timeline_file": {"type": "string"}},
            "required": ["timeline_file"],
            "additionalProperties": False,
        },
        "handler": inspect_timeline,
    },
    "validate_timeline": {
        "description": "Validate an MCP timeline for overlaps, duration mismatches, linked clip consistency, and media references.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "check_media_exists": {"type": "boolean", "default": True},
                "duration_tolerance": {"type": "number", "default": 0.001},
            },
            "required": ["timeline_file"],
            "additionalProperties": False,
        },
        "handler": validate_timeline,
    },
    "create_timeline_track": {
        "description": "Create an audio or video track in a copy of an MCP timeline.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "track_type": {"type": "string", "enum": ["video", "audio"]},
                "name": {"type": ["string", "null"], "default": None},
                "track_id": {"type": ["string", "null"], "default": None},
                "position": {"type": ["integer", "null"], "default": None},
                "output_directory": {"type": ["string", "null"], "default": None},
                "output_name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "track_type"],
            "additionalProperties": False,
        },
        "handler": create_timeline_track,
    },
    "update_timeline_track": {
        "description": "Rename, lock, or mute a track in a copy of an MCP timeline.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "track_id": {"type": "string"},
                "name": {"type": ["string", "null"], "default": None},
                "locked": {"type": ["boolean", "null"], "default": None},
                "muted": {"type": ["boolean", "null"], "default": None},
                "output_directory": {"type": ["string", "null"], "default": None},
                "output_name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "track_id"],
            "additionalProperties": False,
        },
        "handler": update_timeline_track,
    },
    "remove_timeline_track": {
        "description": "Remove an empty track, or remove a track and its clips when explicitly requested, in a copy of an MCP timeline.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "track_id": {"type": "string"},
                "remove_clips": {"type": "boolean", "default": False},
                "output_directory": {"type": ["string", "null"], "default": None},
                "output_name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "track_id"],
            "additionalProperties": False,
        },
        "handler": remove_timeline_track,
    },
    "add_timeline_clip": {
        "description": "Add a clip reference to a copy of an MCP timeline, optionally creating a linked audio/video clip.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "track_id": {"type": "string"},
                "media": {"type": "string"},
                "source_in": {"type": "number"},
                "source_out": {"type": "number"},
                "timeline_in": {"type": "number"},
                "media_id": {"type": ["string", "null"], "default": None},
                "clip_id": {"type": ["string", "null"], "default": None},
                "speed": {"type": "number", "default": 1.0},
                "create_linked_clip": {"type": "boolean", "default": False},
                "linked_track_id": {"type": ["string", "null"], "default": None},
                "source_segment_id": {"type": ["string", "null"], "default": None},
                "reason": {"type": ["string", "null"], "default": None},
                "output_directory": {"type": ["string", "null"], "default": None},
                "output_name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": True},
            },
            "required": ["timeline_file", "track_id", "media", "source_in", "source_out", "timeline_in"],
            "additionalProperties": False,
        },
        "handler": add_timeline_clip,
    },
    "remove_timeline_clip": {
        "description": "Remove a clip from a copy of an MCP timeline, optionally removing its linked audio/video clip and markers.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "clip_id": {"type": "string"},
                "include_linked": {"type": "boolean", "default": True},
                "remove_markers": {"type": "boolean", "default": False},
                "output_directory": {"type": ["string", "null"], "default": None},
                "output_name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "clip_id"],
            "additionalProperties": False,
        },
        "handler": remove_timeline_clip,
    },
    "duplicate_timeline_clip": {
        "description": "Duplicate a clip in a copy of an MCP timeline, optionally duplicating its linked audio/video clip.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "clip_id": {"type": "string"},
                "timeline_in": {"type": ["number", "null"], "default": None},
                "new_clip_id": {"type": ["string", "null"], "default": None},
                "include_linked": {"type": "boolean", "default": True},
                "output_directory": {"type": ["string", "null"], "default": None},
                "output_name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "clip_id"],
            "additionalProperties": False,
        },
        "handler": duplicate_timeline_clip,
    },
    "insert_timeline_gap": {
        "description": "Insert empty time in a copy of an MCP timeline by shifting later clips on selected tracks.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "position": {"type": "number"},
                "duration": {"type": "number"},
                "track_ids": {"type": ["array", "null"], "items": {"type": "string"}, "default": None},
                "track_type": {"type": ["string", "null"], "enum": ["video", "audio", None], "default": None},
                "move_markers": {"type": "boolean", "default": True},
                "output_directory": {"type": ["string", "null"], "default": None},
                "output_name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "position", "duration"],
            "additionalProperties": False,
        },
        "handler": insert_timeline_gap,
    },
    "remove_timeline_gap": {
        "description": "Remove an empty time range in a copy of an MCP timeline by shifting later clips on selected tracks.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "position": {"type": "number"},
                "duration": {"type": "number"},
                "track_ids": {"type": ["array", "null"], "items": {"type": "string"}, "default": None},
                "track_type": {"type": ["string", "null"], "enum": ["video", "audio", None], "default": None},
                "move_markers": {"type": "boolean", "default": True},
                "remove_markers_in_gap": {"type": "boolean", "default": True},
                "output_directory": {"type": ["string", "null"], "default": None},
                "output_name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "position", "duration"],
            "additionalProperties": False,
        },
        "handler": remove_timeline_gap,
    },
    "trim_timeline_clip": {
        "description": "Create a trimmed copy of one MCP timeline clip, optionally including its linked audio/video clip.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "clip_id": {"type": "string"},
                "source_in": {"type": ["number", "null"], "default": None},
                "source_out": {"type": ["number", "null"], "default": None},
                "output_directory": {"type": ["string", "null"], "default": None},
                "name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "include_linked": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "clip_id"],
            "additionalProperties": False,
        },
        "handler": trim_timeline_clip,
    },
    "move_timeline_clip": {
        "description": "Create a moved copy of one MCP timeline clip, optionally including its linked audio/video clip and markers.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "clip_id": {"type": "string"},
                "timeline_in": {"type": "number"},
                "output_directory": {"type": ["string", "null"], "default": None},
                "name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "include_linked": {"type": "boolean", "default": True},
                "move_markers": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "clip_id", "timeline_in"],
            "additionalProperties": False,
        },
        "handler": move_timeline_clip,
    },
    "split_timeline_clip": {
        "description": "Create a split copy of one MCP timeline clip, optionally including its linked audio/video clip.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "clip_id": {"type": "string"},
                "split_at": {"type": "number"},
                "output_directory": {"type": ["string", "null"], "default": None},
                "name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "include_linked": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "clip_id", "split_at"],
            "additionalProperties": False,
        },
        "handler": split_timeline_clip,
    },
    "apply_timeline_edits": {
        "description": "Apply an ordered batch of add/duplicate/remove/trim/move/split/insert_gap/remove_gap operations to an MCP timeline as one validated copy-on-write transaction.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "edits": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "operation": {
                                "type": "string",
                                "enum": ["add", "duplicate", "remove", "trim", "move", "split", "insert_gap", "remove_gap"],
                            },
                            "clip_id": {"type": "string"},
                            "new_clip_id": {"type": "string"},
                            "track_id": {"type": "string"},
                            "track_ids": {"type": "array", "items": {"type": "string"}},
                            "track_type": {"type": "string", "enum": ["video", "audio"]},
                            "media": {"type": "string"},
                            "source_in": {"type": "number"},
                            "source_out": {"type": "number"},
                            "timeline_in": {"type": "number"},
                            "position": {"type": "number"},
                            "duration": {"type": "number"},
                            "split_at": {"type": "number"},
                            "media_id": {"type": "string"},
                            "speed": {"type": "number", "default": 1.0},
                            "create_linked_clip": {"type": "boolean", "default": False},
                            "linked_track_id": {"type": "string"},
                            "source_segment_id": {"type": "string"},
                            "reason": {"type": "string"},
                            "include_linked": {"type": "boolean", "default": True},
                            "move_markers": {"type": "boolean", "default": True},
                            "remove_markers": {"type": "boolean", "default": False},
                            "remove_markers_in_gap": {"type": "boolean", "default": True},
                        },
                        "required": ["operation"],
                        "additionalProperties": False,
                    },
                    "minItems": 1,
                },
                "output_directory": {"type": ["string", "null"], "default": None},
                "name": {"type": ["string", "null"], "default": None},
                "overwrite": {"type": "boolean", "default": False},
                "dry_run": {"type": "boolean", "default": True},
                "check_media_exists": {"type": "boolean", "default": False},
            },
            "required": ["timeline_file", "edits"],
            "additionalProperties": False,
        },
        "handler": apply_timeline_edits,
    },
    "export_timeline_to_mlt_xml": {
        "description": "Export a validated MCP timeline to a draft MLT XML file without claiming Kdenlive project compatibility.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "output_directory": {"type": "string"},
                "name": {"type": "string", "default": "timeline_draft"},
                "overwrite": {"type": "boolean", "default": False},
                "check_media_exists": {"type": "boolean", "default": True},
            },
            "required": ["timeline_file", "output_directory"],
            "additionalProperties": False,
        },
        "handler": export_timeline_to_mlt_xml,
    },
    "export_timeline_to_kdenlive_template": {
        "description": "Export a validated MCP timeline into a .kdenlive draft by copying and filling a real Kdenlive template project.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeline_file": {"type": "string"},
                "template_project": {"type": "string"},
                "output_directory": {"type": "string"},
                "name": {"type": "string", "default": "timeline_draft"},
                "overwrite": {"type": "boolean", "default": False},
                "check_media_exists": {"type": "boolean", "default": True},
            },
            "required": ["timeline_file", "template_project", "output_directory"],
            "additionalProperties": False,
        },
        "handler": export_timeline_to_kdenlive_template,
    },
}
